FROM amazoncorretto:latest

RUN yum update -y && \
    yum install wget -y && \
    wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo && \
    rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key && \
    yum upgrade -y && \
    amazon-linux-extras install epel -y && \
    yum install jenkins -y

EXPOSE 8080

CMD ["java","-jar","/usr/lib/jenkins/jenkins.war"]