FROM node:latest

RUN git clone https://github.com/simplicitesoftware/nodejs-demo.git

WORKDIR /nodejs-demo/

RUN npm install && \
    sed -i "s/localhost/0.0.0.0/g" app.js

EXPOSE 3000

CMD ["npm","start"]