ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.network :private_network, ip: "192.168.56.4"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "minikube"
        vb.memory = "2000"
    end
 end
