apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fullstack
  name: fullstack
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack
  template:
    metadata:
      labels:
        app: fullstack
    spec:
      containers:
        - image: anguisa/backend:latest
          imagePullPolicy: IfNotPresent
          name: backend
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-headless-svc/news"
          volumeMounts:
            - mountPath: "/static-back"
              name: stage-volume
        - image: anguisa/frontend:latest
          imagePullPolicy: IfNotPresent
          name: frontend
          env:
            - name: BACKEND_HOST
              value: "localhost:9000"
            - name: NGINX_ENVSUBST_TEMPLATE_SUFFIX
              value: ".conf"
          volumeMounts:
            - mountPath: "/static-front"
              name: stage-volume
      terminationGracePeriodSeconds: 30
      volumes:
        - name: stage-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: fullstack
  namespace: test
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      nodePort: 32181
  selector:
    app: fullstack
  type: NodePort