{
 "title": "NodeExporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info, instance)"
    }
   },
   { "name": "acc", "query": "1m,5m,15m,1h" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage, %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\",instance=~\"$instance\"}[$acc])))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\",instance=\"nodeexporter:9100\"}[1m])))"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\", job=\"nodeexporter\"}",
     "legendFormat": "LA1"
    },
    {
     "expr": "node_load5{instance=~\"$instance\", job=\"nodeexporter\"}",
     "legendFormat": "LA5"
    },
    {
     "expr": "node_load15{instance=~\"$instance\", job=\"nodeexporter\"}",
     "legendFormat": "LA15"
    }
   ]
  },
  {
   "title": "RAM Free, %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\",job=\"nodeexporter\"}/node_memory_MemTotal_bytes{instance=~\"$instance\",job=\"nodeexporter\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Disk Free, %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(node_filesystem_avail_bytes{instance=~\"$instance\",job=\"nodeexporter\",device!~\"rootfs|tmpfs|jetbrains-toolbox\"}) by (device) / sum(node_filesystem_size_bytes{instance=~\"$instance\",job=\"nodeexporter\",device!~\"rootfs|tmpfs|jetbrains-toolbox\"}) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}