all:
  hosts:
    cp1:
      ansible_host: 192.168.56.50
      ip: 192.168.56.50
      access_ip: 192.168.56.50
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/olga/docs/projects/devops/vagrant4-kubernetes/.vagrant/machines/cp1/virtualbox/private_key
    node1:
      ansible_host: 192.168.56.51
      ip: 192.168.56.51
      access_ip: 192.168.56.51
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/olga/docs/projects/devops/vagrant4-kubernetes/.vagrant/machines/node1/virtualbox/private_key
    node2:
      ansible_host: 192.168.56.52
      ip: 192.168.56.52
      access_ip: 192.168.56.52
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/olga/docs/projects/devops/vagrant4-kubernetes/.vagrant/machines/node2/virtualbox/private_key
    node3:
      ansible_host: 192.168.56.53
      ip: 192.168.56.53
      access_ip: 192.168.56.53
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/olga/docs/projects/devops/vagrant4-kubernetes/.vagrant/machines/node3/virtualbox/private_key
    node4:
      ansible_host: 192.168.56.54
      ip: 192.168.56.54
      access_ip: 192.168.56.54
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/olga/docs/projects/devops/vagrant4-kubernetes/.vagrant/machines/node4/virtualbox/private_key
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
