apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: anguisa/backend:latest
          imagePullPolicy: IfNotPresent
          name: backend
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-headless-svc/news"
          volumeMounts:
            - mountPath: "/static-back"
              name: prod-backend-volume
      terminationGracePeriodSeconds: 30
      volumes:
        - name: prod-backend-volume
          persistentVolumeClaim:
            claimName: prod-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: test
spec:
  ports:
    - name: back
      port: 9000
  selector:
    app: backend
  type: ClusterIP