---
all:
  hosts:
    nexus-01:
      ansible_host: 51.250.21.160
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: olga
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_ya