stages:
  - build
  - deploy
image: docker:20.10.12
services:
  - docker:20.10.12-dind
builder:
  stage: build
  script:
    - docker build -t python-api-dev:latest .
  except:
    - main
deployer:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/anguisa/gitlab-ci/python-api:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/anguisa/gitlab-ci/python-api:latest
  only:
    - main
