{{- if eq .Values.app.env "prod" -}}
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      protocol: TCP
      nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    app: frontend
  type: NodePort
{{- end }}
