---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 51.250.26.35
    jenkins-agent-01:
      ansible_host: 51.250.22.205
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: olga
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_ya